# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQeLVKAlkRsLRzHDYtayIkKUfTZSF05H
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

def process_car_data(file_name):

    df = pd.read_csv(file_name)

    predictors = ['Year', 'Engine HP', 'Engine Cylinders', 'highway MPG', 'city mpg', 'Popularity']
    target = 'MSRP'

    X = df[predictors]
    y = df[target]

    for col in X.columns:
        X[col] = X[col].fillna(X[col].mean())

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

    lr_model = LinearRegression()
    lr_model.fit(X_train, y_train)

    y_pred_lr = lr_model.predict(X_test)
    rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))

    dumb_prediction = np.full(y_test.shape, y_train.mean())
    rmse_dumb = np.sqrt(mean_squared_error(y_test, dumb_prediction))

    rmse_diff = rmse_dumb - rmse_lr

    result = {
        'Linear Regression RMSE': rmse_lr,
        'Dumb Model RMSE': rmse_dumb,
        'Difference (Dumb - LR)': rmse_diff,
        'LR is better by (RMSE reduction)': rmse_diff,
        'LR is better by (%)': (rmse_diff / rmse_dumb) * 100
    }

    print(f"Линейная регрессия RMSE: {rmse_lr:.2f}")
    print(f"Глупая модель RMSE: {rmse_dumb:.2f}")
    print(f"Разница (глупая - LR): {rmse_diff:.2f}")
    print(f"Линейная регрессия лучше на {rmse_diff:.2f} единиц RMSE")
    print(f"Линейная регрессия лучше на {(rmse_diff / rmse_dumb) * 100:.1f}%")

    return result

if __name__ == "__main__":
    result = process_car_data('data.csv')