# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQeLVKAlkRsLRzHDYtayIkKUfTZSF05H
"""

def check_input(element):
    """Проверяет, является ли элемент строкой."""
    return isinstance(element, str)


def get_substring(s):
    """Находит самую длинную подстроку без повторений в строке s."""
    if not s:
        return ""

    char_index = {}
    start = 0
    max_len = 0
    max_substr = ""

    for i, char in enumerate(s):
        if char in char_index and char_index[char] >= start:
            start = char_index[char] + 1
        char_index[char] = i


        if i - start + 1 > max_len:
            max_len = i - start + 1
            max_substr = s[start:i+1]

    return max_substr


def main(lst):
    """Основная функция: находит самую длинную строку и её самую длинную подстроку без повторений."""

    strings = [(i, elem) for i, elem in enumerate(lst) if check_input(elem)]

    if not strings:
        print(-1, '')
        return


    longest_idx, longest_str = max(strings, key=lambda x: len(x[1]))


    longest_substr = get_substring(longest_str)

    print(f"{longest_idx}, '{longest_substr}'")



if __name__ == "__main__":

    main([[0, 4, 8], 'abca', 7, 'aaaaa'])



    main(['abcabcbb', 'bbbbb', 'pwwkew'])


    main([1, 2, 3, 4])


    main([''])