# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQeLVKAlkRsLRzHDYtayIkKUfTZSF05H
"""

import pandas as pd
import numpy as np
from scipy import stats

def website_analyse(website_visits_december_2024):
    df = pd.read_csv(website_visits_december_2024)

    mean_pages = df['Просмотренные страницы'].mean()
    print(f"1) Среднее количество просмотренных страниц: {mean_pages:.2f}")

    std_time = df['Время на сайте (сек)'].std()
    print(f"2) Стандартное отклонение: {std_time:.2f}")

    mean_time = df['Время на сайте (сек)'].mean()
    cv = std_time / mean_time

    if cv > 0.25:
        variability = "Высокая вариабельность"
    elif cv > 0.1:
        variability = "Умеренная вариабельность"
    else:
        variability = "Слабая вариабельность"

    print(f"3) {variability}: {cv:.4f}")

    mobile_data = df[df['Тип устройства'] == 'Мобильное']['Просмотренные страницы']
    desktop_data = df[df['Тип устройства'] == 'Десктоп']['Просмотренные страницы']

    t_stat, p_value = stats.ttest_ind(mobile_data, desktop_data)

    if p_value > 0.05:
        result = "Нет статистически значимой разницы"
    else:
        result = "Есть статистически значимая разница в количестве страниц"

    print(f"4) {result}: {p_value:.4f}")